/**
 * Portfolio-level deep dive opened from the VP signals board.
 *
 * Extracted from the original 3,982-line SignalsBoard.tsx.
 */
import React from 'react';
import { Activity, X, Brain } from 'lucide-react';
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip, CartesianGrid, Legend, LineChart, Line, BarChart, Bar } from 'recharts';
import { ModalShell } from '../../common/Modal';

export interface PortfolioDeepDiveModalProps {
  isOpen: boolean;
  onClose: () => void;
  metricType: 'overlap' | 'innovation' | 'risk' | null;
  isDarkMode: boolean;
}

export const PortfolioDeepDiveModal: React.FC<PortfolioDeepDiveModalProps> = ({
  isOpen,
  onClose,
  metricType,
  isDarkMode
}) => {
  if (!isOpen || !metricType) return null;

  const getMetricData = () => {
    switch (metricType) {
      case 'overlap':
        return {
          title: 'Beverages Overlap Ratio',
          value: '0.68',
          status: 'High Cannibalization',
          statusColor: 'text-red-500 bg-red-500/10 border-red-500/20 dark:bg-red-500/5 dark:border-red-500/10',
          gaugeColor: '#ef4444',
          description: 'Measures the product/flavour similarity and customer base overlap across our active beverage SKUs. High overlap indicates that our variants are siphoning organic sales from each other rather than capturing new market share.',
          details: [
            { label: 'Primary Contributor', value: 'Mango Fizz 500ml vs 750ml' },
            { label: 'Promo Correlation', value: '-0.62 (High Sales Cannibalization)' },
            { label: 'Monthly Margin Drag', value: '~$1.2M estimated' },
            { label: 'Customer Overlap', value: '74% shared audience' }
          ],
          aiRecommendations: [
            'Consolidate duplicate pack sizes (e.g. phase out overlapping discount runs on the 750ml bottle and focus on the 500ml high-margin pack).',
            'Reposition variant branding: Align Mango Fizz Sugar-Free specifically toward health-conscious young adults and the Classic variant for family sharing.',
            'Establish non-overlapping promotional calendars siphoning SKUs to avoid co-depleting organic demand.'
          ],
          chartData: [
            { name: 'W1', 'Mango Fizz 500ml': 420, 'Mango Fizz 750ml': 380, 'Net Organic': 580 },
            { name: 'W2', 'Mango Fizz 500ml': 460, 'Mango Fizz 750ml': 320, 'Net Organic': 560 },
            { name: 'W3', 'Mango Fizz 500ml': 510, 'Mango Fizz 750ml': 290, 'Net Organic': 540 },
            { name: 'W4', 'Mango Fizz 500ml': 550, 'Mango Fizz 750ml': 260, 'Net Organic': 550 }
          ]
        };
      case 'innovation':
        return {
          title: 'Innovation Volume Share',
          value: '34%',
          status: 'Target > 30% (Outperforming)',
          statusColor: 'text-emerald-500 bg-emerald-500/10 border-emerald-500/20 dark:bg-emerald-500/5 dark:border-emerald-500/10',
          gaugeColor: '#10b981',
          description: 'Tracks the percentage of total sales volume generated by product lines introduced within the last 18 months. Achieving 34% demonstrates rapid consumer adoption and strong market traction for our NPDs.',
          details: [
            { label: 'Leading Launch', value: 'Eco-Pack Mineral Water (BrandF)' },
            { label: 'NPD Adoption Rate', value: '14.2% MoM volume growth' },
            { label: 'Active Innovation SKUs', value: '18 products' },
            { label: 'Contribution to Margin', value: '+3.1% gross margin expansion' }
          ],
          aiRecommendations: [
            'Increase production capacity allocation by 15% for the top-performing Eco-Pack SKU to preempt potential stockouts.',
            'Onboard a domestic secondary supplier in Gujarat to reduce raw material transit time from 28 days to 10 days.',
            'Deploy targeted digital programmatic ad campaigns focusing on the Eco-Pack packaging sustainability claims in metros.'
          ],
          chartData: [
            { name: 'Jan', 'New Products': 28, 'Core Portfolio': 72 },
            { name: 'Feb', 'New Products': 30, 'Core Portfolio': 70 },
            { name: 'Mar', 'New Products': 32, 'Core Portfolio': 68 },
            { name: 'Apr', 'New Products': 31, 'Core Portfolio': 69 },
            { name: 'May', 'New Products': 33, 'Core Portfolio': 67 },
            { name: 'Jun', 'New Products': 34, 'Core Portfolio': 66 }
          ]
        };
      case 'risk':
        return {
          title: 'Portfolio Health Risk Index',
          value: '0.44',
          status: 'Moderate Risk Profile',
          statusColor: 'text-amber-500 bg-amber-500/10 border-amber-500/20 dark:bg-amber-500/5 dark:border-amber-500/10',
          gaugeColor: '#f59e0b',
          description: 'A composite health index scoring the catalog\'s structural risks. Factors include raw materials complexity, single-source dependency, promotional reliance, and supply lead-time volatility.',
          details: [
            { label: 'Primary Risk Driver', value: 'Promo dependency (72% on snacks)' },
            { label: 'Average Lead Time', value: '24.5 days (Target < 15 days)' },
            { label: 'SKU Complexity Count', value: '42 low-velocity SKUs' },
            { label: 'Revenue Under Volatility', value: '$4.2M exposure' }
          ],
          aiRecommendations: [
            'Retire the bottom 10% low-velocity, high-complexity SKUs (e.g. low-margin floor cleaners) to free up warehouse capacity.',
            'Renegotiate wholesale agreements for ingredients to transition snack lines from promo-reliant pricing to everyday low pricing (EDLP).',
            'Pre-position ingredient buffers at primary regional hubs to compress procurement lead time by 30%.'
          ],
          chartData: [
            { name: 'Jan', 'Margin Leakage': 2.4, 'Supply Bottleneck': 1.8, 'Promo Reliance': 3.5 },
            { name: 'Feb', 'Margin Leakage': 2.3, 'Supply Bottleneck': 1.9, 'Promo Reliance': 3.4 },
            { name: 'Mar', 'Margin Leakage': 2.1, 'Supply Bottleneck': 2.2, 'Promo Reliance': 3.6 },
            { name: 'Apr', 'Margin Leakage': 1.9, 'Supply Bottleneck': 2.5, 'Promo Reliance': 3.2 },
            { name: 'May', 'Margin Leakage': 1.8, 'Supply Bottleneck': 2.8, 'Promo Reliance': 3.1 },
            { name: 'Jun', 'Margin Leakage': 1.7, 'Supply Bottleneck': 2.4, 'Promo Reliance': 3.0 }
          ]
        };
      default:
        return null;
    }
  };

  const data = getMetricData();
  if (!data) return null;

  return (
    <ModalShell isOpen onClose={onClose} layer="panel" className="flex items-center justify-center p-4">
      <div className="w-full max-w-2xl bg-white dark:bg-zinc-900 border border-black/10 dark:border-white/15 p-6 rounded shadow-2xl flex flex-col gap-5 text-xs max-h-[90vh] overflow-y-auto">
        
        {/* Header */}
        <div className="flex justify-between items-center border-b border-black/15 dark:border-white/15 pb-3">
          <div className="flex items-center gap-2">
            <Activity size={18} className="text-[#6d28d9] dark:text-[#a78bfa]" />
            <div>
              <span className="text-[10px] font-extrabold uppercase tracking-widest text-zinc-400">System Metric Deep Dive</span>
              <h3 className="text-[15px] font-display font-bold text-zinc-800 dark:text-zinc-100 leading-tight">
                {data.title}
              </h3>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-1 hover:bg-black/5 dark:hover:bg-white/5 rounded text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-200 cursor-pointer border-none bg-transparent"
          >
            <X size={16} />
          </button>
        </div>

        {/* Overview */}
        <div className="grid grid-cols-1 md:grid-cols-12 gap-4 items-center">
          <div className="md:col-span-4 flex flex-col items-center p-4 bg-zinc-50 dark:bg-zinc-800/40 rounded border border-black/5 dark:border-white/5">
            <svg viewBox="0 0 120 70" className="w-24 h-14">
              <path
                d="M 15 60 A 45 45 0 0 1 105 60"
                fill="none"
                stroke={isDarkMode ? "rgba(255,255,255,0.08)" : "rgba(0,0,0,0.06)"}
                strokeWidth="10"
                strokeLinecap="round"
              />
              <path
                d="M 15 60 A 45 45 0 0 1 105 60"
                fill="none"
                stroke={data.gaugeColor}
                strokeWidth="10"
                strokeLinecap="round"
                strokeDasharray={141.37}
                strokeDashoffset={141.37 * (1 - (metricType === 'innovation' ? 0.34 : metricType === 'overlap' ? 0.68 : 0.44))}
              />
            </svg>
            <span className="text-2xl font-display font-extrabold mt-1" style={{ color: data.gaugeColor }}>{data.value}</span>
            <span className={`px-2.5 py-0.5 rounded-full text-[8.5px] font-bold uppercase tracking-wider mt-1.5 border ${data.statusColor}`}>
              {data.status}
            </span>
          </div>
          <div className="md:col-span-8 space-y-2">
            <h4 className="text-[11px] font-bold text-zinc-700 dark:text-zinc-300 uppercase tracking-wider">Metric Definition & Context</h4>
            <p className="text-zinc-500 dark:text-zinc-400 leading-relaxed text-[10.5px]">
              {data.description}
            </p>
          </div>
        </div>

        {/* Details Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 bg-zinc-50 dark:bg-zinc-800/40 rounded border border-black/5 dark:border-white/5 space-y-3">
            <h4 className="text-[10px] font-bold text-zinc-700 dark:text-zinc-400 uppercase tracking-wider border-b border-black/5 dark:border-white/5 pb-1">Key Diagnostic Metrics</h4>
            <div className="space-y-2">
              {data.details.map((d, i) => (
                <div key={i} className="flex justify-between items-center text-[10px]">
                  <span className="text-zinc-400">{d.label}</span>
                  <span className="font-bold text-zinc-800 dark:text-zinc-200">{d.value}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="p-4 bg-zinc-50 dark:bg-zinc-800/40 rounded border border-black/5 dark:border-white/5 space-y-3">
            <h4 className="text-[10px] font-bold text-[#6d28d9] dark:text-[#a78bfa] uppercase tracking-wider border-b border-black/5 dark:border-white/5 pb-1 flex items-center gap-1">
              <Brain size={12} />
              AI Strategic Recommendations
            </h4>
            <ul className="list-disc pl-4 space-y-1.5 text-zinc-500 dark:text-zinc-400 text-[10px] leading-relaxed">
              {data.aiRecommendations.map((r, i) => (
                <li key={i}>{r}</li>
              ))}
            </ul>
          </div>
        </div>

        {/* Chart */}
        <div className="p-4 bg-zinc-50 dark:bg-zinc-800/40 rounded border border-black/5 dark:border-white/5 space-y-3">
          <h4 className="text-[10px] font-bold text-zinc-700 dark:text-zinc-400 uppercase tracking-wider border-b border-black/5 dark:border-white/5 pb-1">Performance Trend & Simulations</h4>
          <div className="h-44">
            <ResponsiveContainer width="100%" height="100%">
              {metricType === 'overlap' ? (
                <AreaChart data={data.chartData as any} margin={{ left: -25, right: 5, top: 10, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke={isDarkMode ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)'} vertical={false} />
                  <XAxis dataKey="name" tick={{ fill: isDarkMode ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.4)', fontSize: 9 }} axisLine={false} tickLine={false} />
                  <YAxis tick={{ fill: isDarkMode ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.4)', fontSize: 9 }} axisLine={false} tickLine={false} />
                  <Tooltip contentStyle={{ backgroundColor: isDarkMode ? '#1f1f1f' : '#fff', border: isDarkMode ? '1px solid rgba(255,255,255,0.1)' : '1px solid rgba(0,0,0,0.1)', color: isDarkMode ? '#fff' : '#000', fontSize: 9 }} />
                  <Legend wrapperStyle={{ fontSize: 9 }} />
                  <Area type="monotone" dataKey="Mango Fizz 500ml" stroke="#ef4444" fill="rgba(239, 68, 68, 0.1)" strokeWidth={1.5} />
                  <Area type="monotone" dataKey="Mango Fizz 750ml" stroke="#f59e0b" fill="rgba(245, 158, 11, 0.1)" strokeWidth={1.5} />
                  <Area type="monotone" dataKey="Net Organic" stroke="#10b981" fill="rgba(16, 185, 129, 0.1)" strokeWidth={2} strokeDasharray="4 4" />
                </AreaChart>
              ) : metricType === 'innovation' ? (
                <BarChart data={data.chartData as any} margin={{ left: -25, right: 5, top: 10, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke={isDarkMode ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)'} vertical={false} />
                  <XAxis dataKey="name" tick={{ fill: isDarkMode ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.4)', fontSize: 9 }} axisLine={false} tickLine={false} />
                  <YAxis tick={{ fill: isDarkMode ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.4)', fontSize: 9 }} axisLine={false} tickLine={false} />
                  <Tooltip contentStyle={{ backgroundColor: isDarkMode ? '#1f1f1f' : '#fff', border: isDarkMode ? '1px solid rgba(255,255,255,0.1)' : '1px solid rgba(0,0,0,0.1)', color: isDarkMode ? '#fff' : '#000', fontSize: 9 }} />
                  <Legend wrapperStyle={{ fontSize: 9 }} />
                  <Bar dataKey="New Products" stackId="a" fill="#10b981" />
                  <Bar dataKey="Core Portfolio" stackId="a" fill={isDarkMode ? 'rgba(255,255,255,0.15)' : 'rgba(0,0,0,0.15)'} />
                </BarChart>
              ) : (
                <LineChart data={data.chartData as any} margin={{ left: -25, right: 5, top: 10, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke={isDarkMode ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)'} vertical={false} />
                  <XAxis dataKey="name" tick={{ fill: isDarkMode ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.4)', fontSize: 9 }} axisLine={false} tickLine={false} />
                  <YAxis tick={{ fill: isDarkMode ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.4)', fontSize: 9 }} axisLine={false} tickLine={false} />
                  <Tooltip contentStyle={{ backgroundColor: isDarkMode ? '#1f1f1f' : '#fff', border: isDarkMode ? '1px solid rgba(255,255,255,0.1)' : '1px solid rgba(0,0,0,0.1)', color: isDarkMode ? '#fff' : '#000', fontSize: 9 }} />
                  <Legend wrapperStyle={{ fontSize: 9 }} />
                  <Line type="monotone" dataKey="Margin Leakage" stroke="#ef4444" strokeWidth={1.5} dot={false} />
                  <Line type="monotone" dataKey="Supply Bottleneck" stroke="#3b82f6" strokeWidth={1.5} dot={false} />
                  <Line type="monotone" dataKey="Promo Reliance" stroke="#f59e0b" strokeWidth={1.5} dot={false} />
                </LineChart>
              )}
            </ResponsiveContainer>
          </div>
        </div>

        {/* Footer */}
        <div className="flex justify-end pt-2 border-t border-black/10 dark:border-white/10">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-acies-gray hover:bg-acies-yellow hover:text-acies-gray text-white text-[9px] font-extrabold uppercase tracking-widest rounded-sm transition-all cursor-pointer border-none"
          >
            Close Deep Dive
          </button>
        </div>

      </div>
    </ModalShell>
  );
};
